### ISSUE TITLE
When I use "option(ENABLE_TEASER "Build with Teaser++" ON)".Then excute catkin_make, the terminal show " fatal error: pcl/features/fpfh.h: No such file or directory #include <pcl/features/fpfh.h>"?

### ISSUE THREAD

**Issue by kaitaotang** [koide3/hdl_global_localization#11]
When I use "option(ENABLE_TEASER "Build with Teaser++" ON)" at CMakeLists. Then I execute catkin_make, the terminal show "No such file or directory  #include <pcl/features/fpfh.h> ". However, I have install pcl-1.8 and melodic in Ubuntu18.04 docker. I ensure I have fpfh.h at direction "/usr/include/pcl-1.8/pcl/features/fpfh.h ". The error message is as follows:

> In file included from /home/tang/tang/rover_slam/build/ROVER_SLAM/hdl_global_localization/teaser-prefix/src/teaser/teaser/src/fpfh.cc:9:0:
/home/tang/tang/rover_slam/build/ROVER_SLAM/hdl_global_localization/teaser-prefix/src/teaser/teaser/include/teaser/fpfh.h:12:10: fatal error: pcl/features/fpfh.h: No such file or directory
 #include <pcl/features/fpfh.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
teaser/CMakeFiles/teaser_features.dir/build.make:62: recipe for target 'teaser/CMakeFiles/teaser_features.dir/src/fpfh.cc.o' failed
make[5]: *** [teaser/CMakeFiles/teaser_features.dir/src/fpfh.cc.o] Error 1
CMakeFiles/Makefile2:560: recipe for target 'teaser/CMakeFiles/teaser_features.dir/all' failed
make[4]: *** [teaser/CMakeFiles/teaser_features.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[ 15%] Building CXX object pmc-build/CMakeFiles/pmc.dir/pmc_maxclique.cpp.o
[ 18%] Building CXX object pmc-build/CMakeFiles/pmc.dir/pmcx_maxclique.cpp.o
[ 21%] Building CXX object pmc-build/CMakeFiles/pmc.dir/pmcx_maxclique_basic.cpp.o
[ 25%] Building CXX object pmc-build/CMakeFiles/pmc.dir/pmc_cores.cpp.o
[ 28%] Linking CXX shared library libtinyply.so
[ 28%] Built target tinyply
[ 31%] Building CXX object pmc-build/CMakeFiles/pmc.dir/pmc_utils.cpp.o
[ 34%] Building CXX object pmc-build/CMakeFiles/pmc.dir/pmc_graph.cpp.o
[ 37%] Building CXX object pmc-build/CMakeFiles/pmc.dir/pmc_clique_utils.cpp.o
[ 40%] Linking CXX shared library libpmc.so
[ 40%] Built target pmc
[ 43%] Linking CXX static library libgtest.a
[ 43%] Built target gtest
Makefile:129: recipe for target 'all' failed
make[3]: *** [all] Error 2
ROVER_SLAM/hdl_global_localization/CMakeFiles/teaser.dir/build.make:110: recipe for target 'ROVER_SLAM/hdl_global_localization/teaser-prefix/src/teaser-stamp/teaser-build' failed
make[2]: *** [ROVER_SLAM/hdl_global_localization/teaser-prefix/src/teaser-stamp/teaser-build] Error 2
CMakeFiles/Makefile2:4120: recipe for target 'ROVER_SLAM/hdl_global_localization/CMakeFiles/teaser.dir/all' failed
make[1]: *** [ROVER_SLAM/hdl_global_localization/CMakeFiles/teaser.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4" failed

How can I fixed this problem?

**Comment by MasterY0416** [comment]
Hi, do you remember how you solved the problem, is it the version of PCL? Need to use 1.9.1
