### ISSUE TITLE
Fail to change engine with FPFH_TEASER

### ISSUE THREAD

**Issue by DAR-fly** [koide3/hdl_global_localization#15]
Hi,@koide3 
Thanks for your great job in hdl_global_localization.I success run the global_localization with rosservice /relocalize,and it performs great in my own 3D pcdmap.But when i change the engine from FPFH_RANSAC to FPFH_TEASER,then catkin_make and the terminal has some error:

- [ INFO] [1682495057.978073775]: Start Global Localization Node
[ INFO] [1682495057.980986173]: Initializing nodelet with 12 worker threads.
**[ERROR] [1682495057.985300268]: Unknown Global Localization Engine:FPFH_TEASER**
[ INFO] [1682495058.214123043]: create registration method for localization
[ INFO] [1682495058.215627533]: NDT_OMP is selected
[ INFO] [1682495058.215741877]: search_method DIRECT7 is selected
[ INFO] [1682495058.215750812]: create registration method for fallback during relocalization
[ INFO] [1682495058.216961176]: NDT_OMP is selected
[ INFO] [1682495058.216971597]: search_method DIRECT7 is selected
[ INFO] [1682495058.217276848]: initialize pose estimator with specified parameters!!
[ INFO] [1682495058.224749614]: wait for global localization services
[ INFO] [1682495059.212321040]: globalmap received!
[ INFO] [1682495059.255172053]: set globalmap for global localization!
[ INFO] [1682495059.261228271]: Global Map Received
[ INFO] [1682495059.409694719]: failed to set global map
**[hdl_global_localization-2] process has died [pid 1781230, exit code -11, cmd /home/clf/hdl_global_localization/devel/lib/hdl_global_localization/hdl_global_localization_node __name:=hdl_global_localization __log:=/home/clf/.ros/log/25ddf258-e406-11ed-94aa-ddd2548f4cbe/hdl_global_localization-2.log].
log file: /home/clf/.ros/log/25ddf258-e406-11ed-94aa-ddd2548f4cbe/hdl_global_localization-2*.log**

And I also set ENABLE_TEASER=ON.How to fix this problem?Thanks a lot!

**Comment by koide3** [comment]
Can you try the following? Note that I didn't extensively test FPFH_TEASER, and there might be some installation issues.

```bash
catkin_make -DENABLE_TEASER=ON
```

**Comment by DAR-fly** [comment]
Hi， @koide3 .It's my fault.I didn't explain the problem well.During catkin_make,it run succeed.The error occured with 
` roslaunch hdl_localization hdl_localization.launch 
`

**Comment by koide3** [comment]
I think the error ```Unknown Global Localization Engine:FPFH_TEASER``` should not appear if cmake is properly configured. Can you try to manually comment out ```if(ENABLE_TEASER)``` to force enabling it?

**Comment by DAR-fly** [comment]
That's right.I sloved this problem with 
`catkin_make -DENABLE_TEASER=ON`
Then roslaunch and there is no mistake.It seems that setting ENABLE_TEASER=ON doesn't work on catkin_make.
Thank you for you reply!Closing this issue now.
