### ISSUE TITLE
Unable to set engine type 

### ISSUE THREAD

**Issue by yutouwd** [koide3/hdl_global_localization#2]
Hello @koide3 ,

Thank you for your great work. I can use the global localization now. But when I try to change the global localization engine, it has some error (in the right upper terminal):

![Screenshot from 2021-01-20 15-16-05](https://user-images.githubusercontent.com/6382417/105141436-1abdb780-5b34-11eb-9985-22f4987558b3.png)

Another question is after I run ```rosservice call /relocalize```, The terminal would output:

```
[ INFO] [1611127781.690363903, 1563976074.256382391]: Query Global Localization
[ INFO] [1611127781.705907303, 1563976074.266465002]: Query 53 points
[ INFO] [1611127781.707902465, 1563976074.276539921]: Resolution trans:16 theta:0.0333349
[ INFO] [1611127781.708019880, 1563976074.276539921]: TransX range:-4 4
[ INFO] [1611127781.708191889, 1563976074.276539921]: TransY range:-4 4
[ INFO] [1611127781.708326331, 1563976074.276539921]: Theta  range:-95 95
[ INFO] [1611127781.712237307, 1563976074.276539921]: Initial transformation set size:15471
[ INFO] [1611127782.641870995, 1563976075.211462633]: Branch-and-Bound
```

What's does ```TransX range``` mean? Is it the range of relocalize? And can I change these parameters?

**Comment by koide3** [comment]
Hi @yutouwd ,

Regarding the ros service errors, maybe you need to do ```source /your/catkin_ws/devel/setup.bash``` to let ROS recognize the service types.

```TransX range``` is the transformation search range at the top level of the global map pyramid. The real search range is given by ```TransX * resolution * 2^(pyramid_level - 1)``` (with the default params, it will be ```4 * 0.5 * 2^(6-1) = 64m```).

You can enlarge (or shrink) the search range by changing params in ```config/bbs_config.yaml```. Then, ```TransX``` is automatically calculated such that it covers the given search range.

https://github.com/koide3/hdl_global_localization/blob/master/config/bbs_config.yaml
