### ISSUE TITLE
search window of bbs

### ISSUE THREAD

**Issue by narutojxl** [koide3/hdl_global_localization#4]
Hi author, 
Thanks for your sharing firstly :) 
I have a question about search window meaning in config params about `bbs/min_tx, bbs/max_tx`, `*_ty` and `*_theta`. We use the candidates in the search window to transform the query sliced scan points, and then match with map's grid_map, whose resolution is the same with scoring candidate's resolution in [BBSLocalization::localize()](https://github.com/koide3/hdl_global_localization/blob/master/src/hdl_global_localization/bbs/bbs_localization.cpp#L89).  If the query scan's sensor frame doesn't in the search window of the map frame, it seems that we can not get correct result, right?  But to a certain extent, we can use this lib to relocalize the current scan's initial pose(x, y, theta) in map when we lost ourself's location.  
I'm not sure if it’s right to understand as this, thanks for your any reply and help !

**Comment by koide3** [comment]
> If the query scan's sensor frame doesn't in the search window of the map frame, it seems that we can not get correct result, right?

Right. The sensor pose to be estimated must be within the search range. 

> But to a certain extent, we can use this lib to relocalize the current scan's initial pose(x, y, theta) in map when we lost ourself's location.

Yes, as long as the search range sufficiently covers the entire map, we can use it for finding the current location. Indeed, the original paper of Cartographer used this method for relocalization and loop closure detection.

**Comment by narutojxl** [comment]
Thanks author for your detailed reply, my problem is solved, close it now.
