### ISSUE TITLE
combination with hdl_localization and move_base to autonomously move robot

### ISSUE THREAD

**Issue by Magmanat** [koide3/hdl_global_localization#6]
hi i would like to use this hdl_localization with move_base and by the pictures i see that this package already publishes a 2d map, i was wondering if the 2d map has some areas where we wanted to edit such as maybe there was dynamic obstacles in that area which causes some black pixels to appear in the map would we be able to edit this map? if unable to do so, how should i implement it such that i can get a 2D map from hdl to use move_base with?

**Comment by koide3** [comment]
When I used hdl_localization with move_base, I created a 2D map with [this](https://github.com/koide3/pointcloud_to_2dmap), and let move_base take care of dynamic obstacles by feeding 2D scans to it (given by [pointcloud_to_laserscan](http://wiki.ros.org/pointcloud_to_laserscan)).

**Comment by Magmanat** [comment]
For some reason i couldnt compile that, so instead i used pcd to pointcloud and octomap_server to save the 2D map and publish it via map_server thanks for the help!
